--Task 1
SELECT NAME FROM CLASSES
JOIN SHIPS
ON CLASSES.CLASS = SHIPS.CLASS
where DISPLACEMENT > 50000


--Task 2
SELECT NAME, DISPLACEMENT, NUMGUNS FROM ships
JOIN CLASSES
ON ships.CLASS = CLASSES.CLASS
JOIN OUTCOMES
ON OUTCOMES.SHIP = NAME
WHERE BATTLE = 'Guadalcanal'


--Task 3
SELECT distinct cl1.country FROM CLASSES AS cl1
join CLASSES as cl2
on cl1.[TYPE] != cl2.[TYPE] and cl1.COUNTRY = cl2.COUNTRY


--Task 4
SELECT o1.SHIP FROM BATTLES AS b1
JOIN OUTCOMES as o1
ON NAME = BATTLE and result = 'damaged'
JOIN OUTCOMES as o2
on o1.SHIP = o2.SHIP
join BATTLES as b2
on b2.[NAME] = o2.BATTLE
where b1.[DATE] < b2.[DATE]