--TASK 1
select Title, Name from MOVIEEXEC
join movie
on movie.PRODUCERC# = MOVIEEXEC.CERT#
where PRODUCERC# = (select m1.PRODUCERC# from MOVIE as m1
					where title = 'Star Wars')

--TASK 2
select distinct Name from MOVIEEXEC
join movie 
on CERT# = PRODUCERC#
join STARSIN 
on TITLE = MOVIETITLE
where STARNAME = 'Harrison Ford'

--TASK 3
SELECT DISTINCT NAME, STARNAME FROM STUDIO
JOIN MOVIE
ON NAME = MOVIE.STUDIONAME
JOIN STARSIN 
ON MOVIE.TITLE = STARSIN.MOVIETITLE
ORDER BY NAME

--TASK 4
SELECT STARNAME, NETWORTH, TITLE FROM STARSIN
JOIN MOVIE
ON STARSIN.MOVIETITLE = MOVIE.TITLE
JOIN MOVIEEXEC
ON MOVIEEXEC.CERT# = MOVIE.PRODUCERC#
WHERE NETWORTH >= ALL (SELECT ME2.NETWORTH FROM STARSIN
JOIN MOVIE
ON STARSIN.MOVIETITLE = MOVIE.TITLE
JOIN MOVIEEXEC AS ME2
ON MOVIEEXEC.CERT# = MOVIE.PRODUCERC#)

--TASK 5
SELECT NAME, MOVIETITLE FROM MOVIESTAR
LEFT JOIN STARSIN
ON NAME = STARNAME
WHERE STARNAME IS NULL