--TASK 1
select * from CLASSES
right join ships
on CLASSES.CLASS = SHIPS.CLASS

--TASK 2
select * from CLASSES
RIGHT join ships
on CLASSES.CLASS = SHIPS.CLASS

UNION

select * from CLASSES
LEFT join ships
on CLASSES.CLASS = SHIPS.CLASS
WHERE SHIPS.CLASS IS NULL AND CLASSES.CLASS IN (SELECT NAME FROM SHIPS)


--TASK 3
SELECT COUNTRY, NAME FROM CLASSES
JOIN (
select * from ships
left join OUTCOMES
ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.SHIP IS NULL) AS T
ON CLASSES.CLASS = T.CLASS
ORDER BY COUNTRY

--TASK 4
SELECT NAME AS 'Ship Name'
FROM SHIPS
JOIN CLASSES
ON SHIPS.CLASS = CLASSES.CLASS
WHERE NUMGUNS >= 7 AND SHIPS.LAUNCHED = 1916


--TASK 5
SELECT ship, BATTLE, date FROM OUTCOMES
JOIN BATTLES
ON OUTCOMES.BATTLE = BATTLES.NAME
WHERE RESULT = 'sunk'

--TASK 6
select name, DISPLACEMENT,LAUNCHED from ships
join CLASSES
on ships.CLASS = CLASSES.CLASS
where ships.NAME = CLASSes.CLASS

--TASK 7
select * from CLASSES
left join ships
on CLASSES.CLASS = SHIPS.CLASS
where name is null

--TASK 8
SELECT NAME, DISPLACEMENT, NUMGUNS, RESULT FROM OUTCOMES
JOIN SHIPS
ON SHIP = NAME
JOIN CLASSES
ON SHIPS.CLASS = CLASSES.CLASS
WHERE BATTLE = 'North Atlantic'
