--TASK 1
select title,year, length from movie
where (length > 120 or LENGTH is null) and year < 2000

--TASK 2
SELECT NAME, GENDER FROM MOVIESTAR
WHERE NAME LIKE 'J%' AND YEAR(BIRTHDATE) > 1948
ORDER BY NAME DESC

--TASK 3
SELECT T.NAME, COUNT(NAME) AS num_actors FROM (SELECT NAME, STARNAME FROM STUDIO
								JOIN MOVIE 
								ON STUDIONAME = NAME
								JOIN STARSIN
								ON TITLE = MOVIETITLE
								GROUP BY NAME, STARNAME) AS T
GROUP BY NAME								

--TASK 4
SELECT STARNAME, COUNT(STARNAME) AS num_movies FROM STUDIO
JOIN MOVIE 
ON STUDIONAME = NAME
JOIN STARSIN
ON TITLE = MOVIETITLE
GROUP BY STARNAME


--TASK 5
SELECT NAME, TITLE, YEAR FROM STUDIO
JOIN MOVIE
ON STUDIONAME = NAME
WHERE YEAR IN (SELECT MAX(YEAR) FROM STUDIO AS S
				JOIN MOVIE AS M
				ON M.STUDIONAME = S.NAME
				WHERE M.STUDIONAME = STUDIONAME
				GROUP BY S.NAME)

--TASK 6
SELECT NAME FROM MOVIESTAR
WHERE GENDER = 'M' AND 
YEAR(BIRTHDATE) >= ALL (SELECT YEAR(BIRTHDATE) FROM MOVIESTAR WHERE GENDER = 'M')

--TASK 7
SELECT STUDIONAME AS STUDIONAME, STARNAME AS STARNAME, COUNT(STARNAME) AS NUM_MOVIES FROM STARSIN
JOIN MOVIE 
ON TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
GROUP BY STUDIONAME, STARNAME
HAVING COUNT(STARNAME) >= ALL (SELECT COUNT(STARNAME) FROM STARSIN
							JOIN MOVIE 
							ON TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
							GROUP BY STUDIONAME, STARNAME)

--TASK 8
SELECT TITLE, MOVIEYEAR, COUNT(TITLE) AS NUM_ACTORS FROM MOVIE
JOIN STARSIN
ON TITLE = MOVIETITLE AND MOVIEYEAR = YEAR
GROUP BY TITLE, MOVIEYEAR
HAVING COUNT(TITLE) > 2
